$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$rolesJson = Join-Path $root 'assets\data\roles.json'
$outFile = Join-Path $root 'ROLE_PER_ROLE_REPORT.md'

if (-not (Test-Path $rolesJson)) {
  throw "roles.json not found at $rolesJson"
}

$rolesDoc = Get-Content $rolesJson -Raw | ConvertFrom-Json
$roles = @($rolesDoc.roles | Where-Object { $_.id -ne 'host' -and $_.id -ne 'temp' })

$engineFiles = @(
  'lib\logic\game_engine.dart',
  'lib\logic\script_builder.dart',
  'lib\models\player.dart'
) | ForEach-Object { Join-Path $root $_ }

$testFiles = Get-ChildItem (Join-Path $root 'test') -Recurse -Filter '*_test.dart' | Select-Object -ExpandProperty FullName

function RelPath([string]$path) {
  $uriRoot = [Uri]((Resolve-Path $root).Path + [IO.Path]::DirectorySeparatorChar)
  $uriPath = [Uri]((Resolve-Path $path).Path)
  return $uriRoot.MakeRelativeUri($uriPath).ToString().Replace('/', '/')
}

function Find-Mentions([string[]]$paths, [string]$roleId) {
  $escaped = [Regex]::Escape($roleId)
  # "word boundary" that treats underscore as a word char
  $pattern = "(?<![A-Za-z0-9_])$escaped(?![A-Za-z0-9_])"

  $hits = @()
  foreach ($p in $paths) {
    if (-not (Test-Path $p)) { continue }
    $matches = Select-String -Path $p -Pattern $pattern -AllMatches -ErrorAction SilentlyContinue
    foreach ($m in $matches) {
      $hits += [PSCustomObject]@{
        Path = $p
        LineNumber = $m.LineNumber
        Line = ($m.Line.Trim())
      }
    }
  }
  return $hits
}

function Dump-Sample([System.Text.StringBuilder]$sb, [string]$title, $hits, [int]$maxLines, [int]$maxPerFile) {
  [void]$sb.AppendLine("**$title**")
  if (-not $hits -or $hits.Count -eq 0) {
    [void]$sb.AppendLine('- (none)')
    [void]$sb.AppendLine('')
    return
  }

  $grouped = $hits | Group-Object Path | Sort-Object Name

  $remaining = $maxLines
  foreach ($g in $grouped) {
    if ($remaining -le 0) { break }
    [void]$sb.AppendLine("- $(RelPath $g.Name)")
    $take = [Math]::Min($maxPerFile, $remaining)
    foreach ($h in ($g.Group | Select-Object -First $take)) {
      $line = $h.Line
      if ($line.Length -gt 160) { $line = $line.Substring(0,157) + '...' }
      [void]$sb.AppendLine("  - L$($h.LineNumber): $line")
      $remaining--
      if ($remaining -le 0) { break }
    }
  }

  $total = $hits.Count
  if ($total -gt $maxLines) {
    [void]$sb.AppendLine("- …($($total - $maxLines) more matches omitted)")
  }
  [void]$sb.AppendLine('')
}

$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine('# Role Per-Role Report')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Generated by `tools/generate_role_report.ps1`.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## What this shows')
[void]$sb.AppendLine('- Role config (from `assets/data/roles.json`)')
[void]$sb.AppendLine('- Where the role is referenced in engine/script/player state')
[void]$sb.AppendLine('- Where the role is referenced in tests')
[void]$sb.AppendLine('- Flags when a role has no obvious wiring (script + engine references)')
[void]$sb.AppendLine('')

$sorted = $roles | Sort-Object name

foreach ($role in $sorted) {
  $roleId = [string]$role.id
  $roleName = [string]$role.name

  $engineHits = Find-Mentions -paths $engineFiles -roleId $roleId
  $testHits = Find-Mentions -paths $testFiles -roleId $roleId

  $hasScriptBuilder = @(
    $engineHits | Where-Object { (Split-Path $_.Path -Leaf) -eq 'script_builder.dart' }
  ).Count -gt 0
  $hasEngine = @(
    $engineHits | Where-Object { (Split-Path $_.Path -Leaf) -eq 'game_engine.dart' }
  ).Count -gt 0
  $hasTests = $testHits.Count -gt 0
  $repeatable = $roleId -in @('dealer','party_animal')

  $abilityText = if ([string]::IsNullOrWhiteSpace([string]$role.ability)) { '(none)' } else { [string]$role.ability }

  [void]$sb.AppendLine("## $roleName (``$roleId``)")
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('**Config**')
  [void]$sb.AppendLine("- alliance: ``$($role.alliance)``")
  [void]$sb.AppendLine("- type: ``$($role.type)``")
  [void]$sb.AppendLine("- night_priority: ``$($role.night_priority)``")
  [void]$sb.AppendLine("- ability: ``$abilityText``")
  if ($null -ne $role.start_alliance) { [void]$sb.AppendLine("- start_alliance: ``$($role.start_alliance)``") }
  if ($null -ne $role.has_binary_choice_at_start) { [void]$sb.AppendLine("- has_binary_choice_at_start: ``$($role.has_binary_choice_at_start)``") }
  if ($role.choices -and $role.choices.Count -gt 0) { [void]$sb.AppendLine("- choices: ``$($role.choices -join ', ')``") }
  [void]$sb.AppendLine("- repeatable: ``$repeatable``")
  [void]$sb.AppendLine('')

  [void]$sb.AppendLine('**Wiring**')
  [void]$sb.AppendLine("- script_builder.dart mention: ``$hasScriptBuilder``")
  [void]$sb.AppendLine("- game_engine.dart mention: ``$hasEngine``")
  [void]$sb.AppendLine("- tests mention: ``$hasTests``")
  [void]$sb.AppendLine('')

  if (-not $hasScriptBuilder -and -not $hasEngine) {
    [void]$sb.AppendLine('**Flag**')
    [void]$sb.AppendLine('- No obvious engine/script wiring found; role may be passive-only or missing integration.')
    [void]$sb.AppendLine('')
  }

  Dump-Sample -sb $sb -title 'Engine / Script Mentions (sample)' -hits $engineHits -maxLines 12 -maxPerFile 3
  Dump-Sample -sb $sb -title 'Test Mentions (sample)' -hits $testHits -maxLines 10 -maxPerFile 3
}

$sb.ToString() | Set-Content -Path $outFile -Encoding UTF8
Write-Host "Wrote $(RelPath $outFile)"